const icons = {
    box: '📦',
    check_blue: '☑️',
    check_green: '✅',
    circle_blue_large: '🔵',
    circle_red: '⭕',
    circle_red_large: '🔴',
    clear: '🧹',
    connect: '🔗 ✔️',
    diamond_blue_large: '🔷',
    diamond_blue_small: '🔹',
    diamond_orange_large: '🔶',
    diamond_orange_small: '🔸',
    disconnect: '🔗 ❌',
    down_blue: '🔽',
    fail: '❌',
    folder: '📂',
    gear: '⚙️',
    hammer: '🔨',
    hourglass_loading: '⏳',
    info: 'ℹ️',
    key: '🔑',
    key_old: '🗝️',
    link: '🔗',
    lock: '🔒',
    lock_key: '🔐',
    pin: '📌',
    recycling: '♻️',
    refresh: '🔄',
    repeat: '🔁',
    rocket: '🚀',
    search: '🔎',
    seed: '🌱',
    skip: '⏭️',
    success: '✔️',
    triangle_red_down: '🔻',
    triangle_red_up: '🔺',
    unlock: '🔓',
    up_blue: '🔼',
    warn: '⚠️',
    wrench: '🔧',
    wrench_hammer: '🛠️'
};

module.exports = icons;
