declare const icons: {
    box: string;
    check_blue: string;
    check_green: string;
    circle_blue_large: string;
    circle_red: string;
    circle_red_large: string;
    clear: string;
    connect: string;
    diamond_blue_large: string;
    diamond_blue_small: string;
    diamond_orange_large: string;
    diamond_orange_small: string;
    disconnect: string;
    down_blue: string;
    fail: string;
    folder: string;
    gear: string;
    hammer: string;
    hourglass_loading: string;
    info: string;
    key: string;
    key_old: string;
    link: string;
    lock: string;
    lock_key: string;
    pin: string;
    recycling: string;
    refresh: string;
    repeat: string;
    rocket: string;
    search: string;
    seed: string;
    skip: string;
    success: string;
    triangle_red_down: string;
    triangle_red_up: string;
    unlock: string;
    up_blue: string;
    warn: string;
    wrench: string;
    wrench_hammer: string;
};

export = icons;
